theme: jekyll-theme-minimal
title: Bienvenidos a la web de smart_climb!
description: smart_climb es un juego de presas inteligentes con las cuales podrás setear rutas desde tu teléfono móvil.

![intro](/images/intro.png)

#Objetivo
El objetivo del proyecto es construir un sistema inteligente de entrenamiento para escalada indoor. El mismo consta de una serie de presas inteligentes y una aplicación para smartphones.
Las presas están equipadas con una luz led RGB, conexión inalámbrica y un sensor de tacto.
La aplicación consta de un tablero donde se podrá setear la ruta y un cronómetro para controlar el tiempo que se demora en la misma.

#Tecnologías a utilizar
* Impresión 3d
* Router CNC
* Escáner 3d
* Microcontroladores
* IoT

#Habilidades a desarrollar
* Modelado 3d
* Casting
* Programación
